Repository voxpupuli/facterdb, pull requests merged in 2021-11, with the labels that each got.

#203 Generate OL/RHEL/SL facts
  README.md
  facts/4.0/oraclelinux-7-x86_64.facts
  facts/4.0/redhat-7-x86_64.facts
  facts/4.0/scientific-7-x86_64.facts
  facts/4.2/oraclelinux-7-x86_64.facts
  facts/4.2/oraclelinux-9-x86_64.facts
  facts/4.2/redhat-7-x86_64.facts
  facts/4.2/redhat-9-x86_64.facts
  facts/4.2/scientific-7-x86_64.facts
Labels: enhancement

#205 Add facter 4.x facts for RockyLinux 8
  README.md
  facts/4.0/rocky-8-x86_64.facts
  facts/4.1/rocky-8-x86_64.facts
  facts/4.2/rocky-8-x86_64.facts
  facts/Vagrantfile
  facts/get_facts.sh
Labels: enhancement

#206 Adding sys-filesystem so that mountpoints fact resolves
  facts/Gemfile
Labels: bug

#204 Release 1.11.0
  CHANGELOG.md
  lib/facterdb/version.rb
Labels: skip-changelog

#209 Add support for ubuntu 21.10 and 21.04
  README.md
  facts/3.14/ubuntu-21.10-x86_64.facts
  facts/4.0/ubuntu-21.04-x86_64.facts
  facts/4.0/ubuntu-21.10-x86_64.facts
  facts/4.1/ubuntu-21.04-x86_64.facts
  facts/4.1/ubuntu-21.10-x86_64.facts
  facts/4.2/ubuntu-21.04-x86_64.facts
  facts/4.2/ubuntu-21.10-x86_64.facts
  facts/Vagrantfile
  facts/get_facts.sh
Labels: enhancement

#210 Re-generating fact sets which were missing the mountpoints fact
  facts/4.0/debian-11-x86_64.facts
  facts/4.0/fedora-32-x86_64.facts
  facts/4.0/fedora-33-x86_64.facts
  facts/4.0/fedora-34-x86_64.facts
  facts/4.0/freebsd-11-x86_64.facts
  facts/4.0/freebsd-12-x86_64.facts
  facts/4.0/freebsd-13-x86_64.facts
  facts/4.0/ubuntu-18.04-x86_64.facts
  facts/4.0/ubuntu-20.04-x86_64.facts
  facts/4.1/debian-11-x86_64.facts
  facts/4.1/fedora-32-x86_64.facts
  facts/4.1/fedora-33-x86_64.facts
  facts/4.1/fedora-34-x86_64.facts
  facts/4.1/freebsd-11-x86_64.facts
  facts/4.1/freebsd-12-x86_64.facts
  facts/4.1/freebsd-13-x86_64.facts
  facts/4.1/ubuntu-18.04-x86_64.facts
  facts/4.1/ubuntu-20.04-x86_64.facts
  facts/4.2/fedora-32-x86_64.facts
  facts/4.2/fedora-33-x86_64.facts
  facts/4.2/freebsd-11-x86_64.facts
  facts/4.2/freebsd-12-x86_64.facts
  facts/4.2/freebsd-13-x86_64.facts
  facts/4.2/ubuntu-18.04-x86_64.facts
  facts/4.2/ubuntu-20.04-x86_64.facts
Labels: bug

#213 Cleanup stdlib/systemd facts and add tests to ensure that they are absent
  facts/2.5/solaris-10-i86pc.facts
  facts/3.11/solaris-10-i86pc.facts
  facts/3.9/solaris-10-i86pc.facts
  facts/4.0/centos-7-x86_64.facts
  facts/4.0/debian-10-x86_64.facts
  facts/4.0/oraclelinux-7-x86_64.facts
  facts/4.0/redhat-7-x86_64.facts
  facts/4.0/scientific-7-x86_64.facts
  facts/4.0/solaris-11-sun4v.facts
  spec/facts_spec.rb
Labels: bug

#214 Release 1.12.0
  CHANGELOG.md
  README.md
  lib/facterdb/version.rb
Labels: skip-changelog

#216 Fix hostname facts for freebsd13 and add spec test
  facts/4.0/freebsd-13-x86_64.facts
  facts/4.1/freebsd-13-x86_64.facts
  facts/4.2/freebsd-13-x86_64.facts
  spec/facts_spec.rb
Labels: bug

#217 Release 1.12.1
  CHANGELOG.md
  lib/facterdb/version.rb
Labels: skip-changelog
