Repository voxpupuli/facterdb, pull requests merged in 2021-12, with the labels that each got.

#218 Adding facts for Fedora 35
  README.md
  facts/4.0/fedora-35-x86_64.facts
  facts/4.1/fedora-35-x86_64.facts
  facts/4.2/fedora-35-x86_64.facts
  facts/Vagrantfile
  facts/get_facts.sh
Labels: enhancement

#219 Add some CentOS 9 legacy facts
  facts/4.2/centos-9-x86_64.facts
  spec/facts_spec.rb
Labels: bug

#220 Oraclelinux/RHEL 9: Add legacy facts
  facts/4.2/oraclelinux-9-x86_64.facts
  facts/4.2/redhat-9-x86_64.facts
  spec/facts_spec.rb
Labels: bug

#222 Add test for legacy FQDN/hostname & correct FQDN/hostname facts
  facts/1.6/amazon-2017-x86_64.facts
  facts/1.6/ubuntu-18.04-aarch64.facts
  facts/1.7/amazon-2017-x86_64.facts
  facts/1.7/centos-9-x86_64.facts
  facts/1.7/ubuntu-18.04-aarch64.facts
  facts/2.0/amazon-2017-x86_64.facts
  facts/2.0/centos-9-x86_64.facts
  facts/2.0/ubuntu-18.04-aarch64.facts
  facts/2.1/amazon-2017-x86_64.facts
  facts/2.1/centos-9-x86_64.facts
  facts/2.1/ubuntu-18.04-aarch64.facts
  facts/2.2/amazon-2017-x86_64.facts
  facts/2.2/centos-9-x86_64.facts
  facts/2.2/ubuntu-18.04-aarch64.facts
  facts/2.3/amazon-2017-x86_64.facts
  facts/2.3/centos-9-x86_64.facts
  facts/2.3/ubuntu-18.04-aarch64.facts
  facts/2.4/amazon-2017-x86_64.facts
  facts/2.4/centos-9-x86_64.facts
  facts/2.4/ubuntu-18.04-aarch64.facts
  facts/2.5/solaris-10-i86pc.facts
  facts/2.5/ubuntu-18.04-aarch64.facts
  facts/3.10/archlinux-x86_64.facts
  facts/3.11/archlinux-x86_64.facts
  facts/3.11/solaris-10-i86pc.facts
  facts/3.12/archlinux-x86_64.facts
  facts/3.14/VirtuozzoLinux-7-x86_64.facts
  facts/3.14/archlinux-x86_64.facts
  facts/3.14/rocky-8-x86_64.facts
  facts/3.14/ubuntu-21.04-x86_64.facts
  facts/3.6/amazon-2017-x86_64.facts
  facts/3.6/pcs-6-x86_64.facts
  facts/3.9/aix-7.1-power.facts
  facts/3.9/archlinux-x86_64.facts
  facts/3.9/solaris-10-i86pc.facts
  facts/4.2/centos-9-x86_64.facts
  facts/4.2/oraclelinux-9-x86_64.facts
  facts/4.2/redhat-9-x86_64.facts
  spec/facts_spec.rb
Labels: bug

#223 Add test for legacy domain fact & Add/correct legacy domain fact
  facts/1.6/amazon-2017-x86_64.facts
  facts/1.6/ubuntu-18.04-aarch64.facts
  facts/1.7/amazon-2017-x86_64.facts
  facts/1.7/ubuntu-18.04-aarch64.facts
  facts/2.0/amazon-2017-x86_64.facts
  facts/2.0/ubuntu-18.04-aarch64.facts
  facts/2.1/amazon-2017-x86_64.facts
  facts/2.1/ubuntu-18.04-aarch64.facts
  facts/2.2/amazon-2017-x86_64.facts
  facts/2.2/ubuntu-18.04-aarch64.facts
  facts/2.3/amazon-2017-x86_64.facts
  facts/2.3/ubuntu-18.04-aarch64.facts
  facts/2.4/amazon-2017-x86_64.facts
  facts/2.4/ubuntu-18.04-aarch64.facts
  facts/2.4/windows-2012 r2-x64.facts
  facts/2.4/windows-7-x64.facts
  facts/2.5/ubuntu-18.04-aarch64.facts
  facts/3.14/ubuntu-21.04-x86_64.facts
  spec/facts_spec.rb
Labels: bug

#224 Validate legacy domain/fqdn/hostname fact on all factsets & Add missing fqdn/domain/hostname fact to all factsets
  facts/3.0/ubuntu-15.10-i386.facts
  facts/3.0/ubuntu-15.10-x86_64.facts
  facts/3.10/ubuntu-18.04-aarch64.facts
  facts/3.2/aix-53-powerpc.facts
  facts/3.2/aix-61-powerpc.facts
  facts/3.2/aix-71-powerpc.facts
  facts/3.6/pcs-6-x86_64.facts
  spec/facts_spec.rb
Labels: bug

#226 Release 1.12.2
  CHANGELOG.md
  lib/facterdb/version.rb
Labels: skip-changelog
