Repository voxpupuli/facterdb, pull requests merged in 2021-07, with the labels that each got.

#174 Fixes #173 - Add AlmaLinux
  README.md
  Rakefile
  facts/3.14/almalinux-8-x86_64.facts
  facts/4.0/almalinux-8-x86_64.facts
  facts/Vagrantfile
  facts/get_facts.sh
Labels: enhancement

#175 Release 1.7.0
  CHANGELOG.md
  Rakefile
  lib/facterdb/version.rb
Labels: skip-changelog

#178 Fix broken GHA release job
  .github/workflows/release.yml
Labels: bug

#179 Add facts for for Darwin 20 (macOS 11) x86_64
  README.md
  facts/3.14/darwin-20-x86_64.facts
  facts/4.2/darwin-20-x86_64.facts
Labels: enhancement

#177 Add CentOS Stream 9 facts
  facts/1.7/centos-9-x86_64.facts
  facts/2.0/centos-9-x86_64.facts
  facts/2.1/centos-9-x86_64.facts
  facts/2.2/centos-9-x86_64.facts
  facts/2.3/centos-9-x86_64.facts
  facts/2.4/centos-9-x86_64.facts
  facts/4.2/centos-9-x86_64.facts
Labels: enhancement
