Repository voxpupuli/facterdb, pull requests merged in 2021-10, with the labels that each got.

#191 get_facts.sh: Collect legacy facts as well
  facts/get_facts.sh
Labels: bug

#193 facter 4.2: Regenerate factsets with legacy facts
  facts/4.2/debian-11-x86_64.facts
  facts/4.2/redhat-8-x86_64.facts
  facts/4.2/ubuntu-18.04-x86_64.facts
  facts/4.2/ubuntu-20.04-x86_64.facts
Labels: bug

#194 facter 4.1: Regenerate factsets with legacy facts
  facts/4.1/debian-11-x86_64.facts
  facts/4.1/freebsd-11-x86_64.facts
  facts/4.1/freebsd-12-x86_64.facts
  facts/4.1/redhat-8-x86_64.facts
  facts/4.1/ubuntu-18.04-x86_64.facts
  facts/4.1/ubuntu-20.04-x86_64.facts
Labels: bug

#197 Release 1.10.1
  CHANGELOG.md
  lib/facterdb/version.rb
Labels: skip-changelog

#199 Add Fedora 33 and 34 factsets
  README.md
  facts/3.14/fedora-34-x86_64.facts
  facts/4.0/fedora-33-x86_64.facts
  facts/4.0/fedora-34-x86_64.facts
  facts/4.1/fedora-33-x86_64.facts
  facts/4.1/fedora-34-x86_64.facts
  facts/4.2/fedora-33-x86_64.facts
  facts/4.2/fedora-34-x86_64.facts
  facts/Vagrantfile
Labels: enhancement
