Repository voxpupuli/facterdb, pull requests merged in 2024-05, with the labels that each got.

#309 Add facts for OpenBSD 7.X for facter 4.7
  facts/4.7/openbsd-7-x86_64.facts
Labels: enhancement

#312 Release 1.25.0
  CHANGELOG.md
  lib/facterdb/version.rb
Labels: skip-changelog

#313 Debian 12: regenerate facter 4.5 factset
  facts/4.5/debian-12-x86_64.facts
  facts/get_facts.sh
Labels: bug

#314 Debian 12: Add facter 4.6/4.7 factset & regenerate facter 4.5 factset
  README.md
  facts/4.6/debian-12-x86_64.facts
  facts/4.7/debian-12-x86_64.facts
  facts/Vagrantfile
Labels: enhancement

#316 get_facts.sh: Remove Debian 12 edgecase
  facts/get_facts.sh
Labels: skip-changelog

#317 get_facts.sh: List all existing Puppet versions
  facts/get_facts.sh
Labels: skip-changelog

#320 Remove +x flag from factsets
  facts/4.0/redhat-8-x86_64.facts
  facts/4.1/redhat-8-x86_64.facts
  facts/4.2/debian-11-x86_64.facts
  facts/4.2/fedora-34-x86_64.facts
Labels: bug

#321 Release 1.26.0
  CHANGELOG.md
  lib/facterdb/version.rb
Labels: skip-changelog

#328 RedHat 8/9: Add IPv6 facts
  facts/3.14/redhat-8-x86_64.facts
  facts/3.14/redhat-9-x86_64.facts
  facts/4.2/redhat-8-x86_64.facts
  facts/4.2/redhat-9-x86_64.facts
  facts/4.3/redhat-8-x86_64.facts
  facts/4.3/redhat-9-x86_64.facts
  facts/4.4/redhat-8-x86_64.facts
  facts/4.4/redhat-9-x86_64.facts
  facts/4.5/redhat-8-x86_64.facts
  facts/4.5/redhat-9-x86_64.facts
  facts/4.6/redhat-8-x86_64.facts
  facts/4.6/redhat-9-x86_64.facts
  facts/4.7/redhat-8-x86_64.facts
  facts/4.7/redhat-9-x86_64.facts
  facts/Vagrantfile
Labels: skip-changelog

#329 Release 1.27.0
  CHANGELOG.md
  lib/facterdb/version.rb
Labels: skip-changelog

#330 get_facts.sh: Drop support for Puppet 7
  facts/get_facts.sh
Labels: backwards-incompatible

#332 Drop EoL Ubuntu 16.04 facts
  README.md
  facts/4.0/ubuntu-16.04-x86_64.facts
  facts/4.1/ubuntu-16.04-x86_64.facts
  facts/4.2/ubuntu-16.04-x86_64.facts
Labels: backwards-incompatible

#331 Drop EoL Debian 9/10 factsets
  README.md
  facts/4.0/debian-10-x86_64.facts
  facts/4.1/debian-10-x86_64.facts
  facts/4.2/debian-10-x86_64.facts
  facts/4.2/debian-9-x86_64.facts
  facts/4.3/debian-10-x86_64.facts
  facts/4.4/debian-10-x86_64.facts
  facts/4.5/debian-10-x86_64.facts
  facts/Vagrantfile
Labels: backwards-incompatible

#333 Drop EoL Fedora 32-35 facts
  README.md
  facts/4.0/fedora-32-x86_64.facts
  facts/4.0/fedora-33-x86_64.facts
  facts/4.0/fedora-34-x86_64.facts
  facts/4.0/fedora-35-x86_64.facts
  facts/4.1/fedora-32-x86_64.facts
  facts/4.1/fedora-33-x86_64.facts
  facts/4.1/fedora-34-x86_64.facts
  facts/4.1/fedora-35-x86_64.facts
  facts/4.2/fedora-32-x86_64.facts
  facts/4.2/fedora-33-x86_64.facts
  facts/4.2/fedora-34-x86_64.facts
  facts/4.2/fedora-35-x86_64.facts
  facts/Vagrantfile
Labels: backwards-incompatible

#339 Fedora: Cleanup package installation
  facts/Vagrantfile
  facts/get_facts.sh
Labels: skip-changelog

#340 Ensure every instance is started with IPv6 enabled
  facts/Vagrantfile
  facts/get_facts.sh
Labels: bug

#345 Drop EoL OracleLinux 6 factset
  README.md
  facts/4.2/oraclelinux-6-x86_64.facts
Labels: backwards-incompatible

#350 deprecate legacy facts
  README.md
Labels: backwards-incompatible

#354 Release 2.0.0
  CHANGELOG.md
  README.md
  Rakefile
  doc/main.md
  lib/facterdb/version.rb
Labels: skip-changelog

#356 CI: Install gems in release workflow
  .github/workflows/release.yml
Labels: skip-changelog

#358 Release 2.0.1
  CHANGELOG.md
  lib/facterdb/version.rb
Labels: skip-changelog
